---

drupal_user: "drupaluser"
drupal_password: "drupalp455w0rd!"
drupal_version: "drupal-7.54"
mysql_bind_address: "127.0.0.1"
drupal_absolute_docroot: "/var/www/yourdomain.app"
civicrm_db: "civicrm"
civicrm_user: "civicrmuser"
civicrm_password: "civicrmp455w0rd!"
civicrm_url: "https://download.civicrm.org/civicrm-4.7.16-drupal.tar.gz?src=donate"
civicrm_destination: "~/civiCRM.tar.gz"


