---

include: ../nginx/defaults/main.yml

drupal_db: "drupal"
drupal_user: "drupaluser"
drupal_password: "drupalp455w0rd!"
drupal_docroot: "/var/www"
drupal_version: "drupal-7.54"
drupal_dir: "{{ domain }}"
drupal_absolute_docroot: "{{ drupal_docroot }}/{{ domain }}"

site_mail: "noreply@{{ domain }}"
site_name: "{{ domain }}"
account_mail: "mymail@domain.com"
user: "compucorp"
password: "123456"